PREFIX?=	/usr/local
BINDIR:=	$(PREFIX)/bin
LIBDIR:=	$(PREFIX)/lib/bsvc

CC?=		gcc
CXX?=		g++
O:=		o
CFLAGS?=	-O -ansi -pedantic -Wall -std=c11 -D_POSIX_C_SOURCE
CXXFLAGS?=	-O -ansi -pedantic -Wall -std=c++11 -D_POSIX_C_SOURCE

WISH?=		wish
AR:=		ar
RANLIB:=	ranlib
RM:=		rm
INSTALL:=	install
STRIP:=		strip
MKDIR:=		mkdir

MKDEP:=		env CC=$(CC) sh mkdep.sh

include GNUMakefile.common
